# Generated by Django 3.0.7 on 2020-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='landlord',
            field=models.BooleanField(default=False),
        ),
    ]
