# Generated by Django 3.0.7 on 2020-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('rent', models.IntegerField()),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField()),
                ('washrooms', models.IntegerField()),
            ],
        ),
    ]
